[tool.black]
target-version = ['py37','py38','py39','py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.env
  | \.e3dc_to_mqtt.egg-info
  | build
  | dist
  | env
)/
'''
line-length = 200

[tool.pylint.messages_control]
disable = "C0330, C0326"